// Omnidex Curated Typography Catalog
// High-legibility, editorial, and atmospheric typefaces with robust offline fallbacks

export const FONT_CATEGORIES = ['All', 'Serif', 'Sans', 'Monospace', 'Atmospheric'];

export const FONT_LIST = [
  {
    id: 'font-sans',
    name: 'Modern Sans',
    typeface: 'Inter',
    category: 'Sans',
    className: 'font-sans',
    tag: 'Default',
    description: 'Clean, neutral, ultra-crisp modern interface typography.',
    previewQuote: 'The quiet sanctum of boundless stories and thought.',
  },
  {
    id: 'font-serif',
    name: 'Literary Serif',
    typeface: 'Merriweather',
    category: 'Serif',
    className: 'font-serif',
    tag: 'Editorial',
    description: 'Warm, pleasant book-face designed for prolonged screen reading.',
    previewQuote: 'A reader lives a thousand lives before he dies.',
  },
  {
    id: 'font-cormorant',
    name: 'Classical Garamond',
    typeface: 'Cormorant Garamond',
    category: 'Serif',
    className: 'font-cormorant',
    tag: 'Timeless',
    description: 'Graceful 16th-century French humanist letterforms with delicate serifs.',
    previewQuote: 'There is no friend as loyal and patient as a book.',
  },
  {
    id: 'font-playfair',
    name: 'Vogue Editorial',
    typeface: 'Playfair Display',
    category: 'Serif',
    className: 'font-playfair',
    tag: 'Haute',
    description: 'High-contrast transitional serif with classical European editorial poise.',
    previewQuote: 'Words are, in my humble opinion, pure magic.',
  },
  {
    id: 'font-crimson',
    name: 'Scholarly Crimson',
    typeface: 'Crimson Pro',
    category: 'Serif',
    className: 'font-crimson',
    tag: 'Academic',
    description: 'Traditional novel and publication proportion with gentle organic warmth.',
    previewQuote: 'Books are a uniquely portable magic across time.',
  },
  {
    id: 'font-lora',
    name: 'Poetic Lora',
    typeface: 'Lora',
    category: 'Serif',
    className: 'font-lora',
    tag: 'Calligraphic',
    description: 'Contemporary serif with fluid calligraphic brushwork and poetic rhythm.',
    previewQuote: 'Whatever our souls are made of, his and mine are the same.',
  },
  {
    id: 'font-spectral',
    name: 'Fine Press Spectral',
    typeface: 'Spectral',
    category: 'Serif',
    className: 'font-spectral',
    tag: 'Fine Press',
    description: 'Crisp editorial precision engineered by Production Type for literary reading.',
    previewQuote: 'I have always imagined that Paradise will be a kind of library.',
  },
  {
    id: 'font-outfit',
    name: 'Geometric Outfit',
    typeface: 'Outfit',
    category: 'Sans',
    className: 'font-outfit',
    tag: 'Modernist',
    description: 'Airy, friendly geometric curves with balanced humanist proportions.',
    previewQuote: 'Simplicity is the ultimate sophistication in prose.',
  },
  {
    id: 'font-jakarta',
    name: 'Jakarta Modern',
    typeface: 'Plus Jakarta Sans',
    category: 'Sans',
    className: 'font-jakarta',
    tag: 'Sharp',
    description: 'High-clarity contemporary neo-grotesque with technical rhythm.',
    previewQuote: 'Clarity and harmony in every phrase and margin.',
  },
  {
    id: 'font-fira',
    name: 'Archival Mono',
    typeface: 'Fira Code',
    category: 'Monospace',
    className: 'font-fira',
    tag: 'Technical',
    description: 'Spacious programmer and archival monospaced letterforms on a strict grid.',
    previewQuote: 'Thought, text, and syntax aligned to the exact character grid.',
  },
  {
    id: 'font-cinzel',
    name: 'Classical Antiquity',
    typeface: 'Cinzel',
    category: 'Atmospheric',
    className: 'font-cinzel',
    tag: 'Mythic',
    description: 'Monumental Roman lapidary inscriptions for epic chronicles and history.',
    previewQuote: 'FORTUNA AUDACES IUVAT — FATE FAVORS THE BOLD.',
  },
  {
    id: 'font-space',
    name: 'Retro Sci-Fi',
    typeface: 'Space Grotesk',
    category: 'Atmospheric',
    className: 'font-space',
    tag: 'Futuristic',
    description: 'Quirky retro-proportional monospace aesthetic for cyberpunk & sci-fi worlds.',
    previewQuote: 'Transmission deciphered across interstellar coordinates.',
  },
];

export const getFontById = (id) =>
  FONT_LIST.find((f) => f.id === id) || FONT_LIST[0];
